//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam_registration_system.Properties
{
    using System;


    namespace exam_registration_system.Properties
    {
        using System;


        /// <summary>
        ///   A strongly-typed resource class, for looking up localized strings, etc.
        /// </summary>
        // This class was auto-generated by the StronglyTypedResourceBuilder
        // class via a tool like ResGen or Visual Studio.
        // To add or remove a member, edit your .ResX file then rerun ResGen
        // with the /str option, or rebuild your VS project.
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        internal class Resources
        {

            private static global::System.Resources.ResourceManager resourceMan;

            private static global::System.Globalization.CultureInfo resourceCulture;

            [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
            internal Resources()
            {
            }

            /// <summary>
            ///   Returns the cached ResourceManager instance used by this class.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            internal static global::System.Resources.ResourceManager ResourceManager
            {
                get
                {
                    if (object.ReferenceEquals(resourceMan, null))
                    {
                        global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("exam_registration_system.Properties.Resources", typeof(Resources).Assembly);
                        resourceMan = temp;
                    }
                    return resourceMan;
                }
            }

            /// <summary>
            ///   Overrides the current thread's CurrentUICulture property for all
            ///   resource lookups using this strongly typed resource class.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            internal static global::System.Globalization.CultureInfo Culture
            {
                get
                {
                    return resourceCulture;
                }
                set
                {
                    resourceCulture = value;
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap _509591040_2313086389208626_706091563171852892_n
            {
                get
                {
                    object obj = ResourceManager.GetObject("509591040_2313086389208626_706091563171852892_n", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap ChatGPT_Image_22_03_46_28_thg_6__2025
            {
                get
                {
                    object obj = ResourceManager.GetObject("ChatGPT Image 22_03_46 28 thg 6, 2025", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap ChatGPT_Image_22_25_51_28_thg_6__2025
            {
                get
                {
                    object obj = ResourceManager.GetObject("ChatGPT Image 22_25_51 28 thg 6, 2025", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap download
            {
                get
                {
                    object obj = ResourceManager.GetObject("download", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap download__1_
            {
                get
                {
                    object obj = ResourceManager.GetObject("download (1)", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap images
            {
                get
                {
                    object obj = ResourceManager.GetObject("images", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap ổ
            {
                get
                {
                    object obj = ResourceManager.GetObject("ổ", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap pngtree_white_rectangle_with_rounded_corner_gray_png_image_10946804
            {
                get
                {
                    object obj = ResourceManager.GetObject("pngtree-white-rectangle-with-rounded-corner-gray-png-image_10946804", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }

            /// <summary>
            ///   Looks up a localized resource of type System.Drawing.Bitmap.
            /// </summary>
            internal static System.Drawing.Bitmap icons8_download_64
            {
                get
                {
                    object obj = ResourceManager.GetObject("icons8-download-64", resourceCulture);
                    return ((System.Drawing.Bitmap)(obj));
                }
            }
        }
    }
